#!/usr/bin/env python3
"""
prepare_bugs4q.py – Prepare the Bugs4Q benchmark dataset.

I download (or validate) the Bugs4Q dataset and convert it into the JSON
format expected by ``src/dataset_loader.py``.

Usage
-----
    python scripts/prepare_bugs4q.py [--source PATH_OR_URL] [--out data/bugs4q]

If you already have the dataset locally, pass the path with ``--source``.
If you want to use the Bugs4Q GitHub release, pass the URL.

I never download data automatically without your explicit ``--source``
argument, to avoid unexpected network calls or large downloads.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import shutil
import sys
from pathlib import Path

# I add the repo root to sys.path so imports work when running directly.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.utils import setup_logging, repo_root

logger = logging.getLogger(__name__)

# I write prepared data here by default.
DEFAULT_OUT = repo_root() / "data" / "bugs4q"

# Official Bugs4Q GitHub repository (for reference; I never auto-download).
BUGS4Q_REPO = "https://github.com/Z-928/Bugs4Q"


def _make_synthetic_dataset(out_dir: Path, n: int = 20) -> None:
    """
    I generate a small synthetic dataset so the pipeline works immediately
    without the real Bugs4Q data.  Each record is clearly labelled as
    synthetic.
    """
    logger.info("Generating %d synthetic records in %s", n, out_dir)
    records = []

    buggy_templates = [
        {
            "source_code": (
                "from qiskit import QuantumCircuit\n"
                "qc = QuantumCircuit(2, 2)\n"
                "qc.h(0)\n"
                "qc.cx(0, 1)\n"
                "# Missing measurement\n"
            ),
            "bug_class": "missing_measurement",
            "location": "synthetic:5",
        },
        {
            "source_code": (
                "from qiskit import QuantumCircuit\n"
                "qc = QuantumCircuit(2, 2)\n"
                "qc.h(0)\n"
                "qc.cx(1, 0)  # Swapped qubits\n"
                "qc.measure([0, 1], [0, 1])\n"
            ),
            "bug_class": "wrong_qubit_order",
            "location": "synthetic:4",
        },
        {
            "source_code": (
                "from qiskit import QuantumCircuit\n"
                "qc = QuantumCircuit(1)\n"
                "qc.u1(3.14, 0)  # Deprecated gate\n"
                "qc.measure_all()\n"
            ),
            "bug_class": "incorrect_gate",
            "location": "synthetic:3",
        },
    ]

    clean_template = {
        "source_code": (
            "from qiskit import QuantumCircuit\n"
            "qc = QuantumCircuit(2, 2)\n"
            "qc.h(0)\n"
            "qc.cx(0, 1)\n"
            "qc.measure([0, 1], [0, 1])\n"
        ),
        "bug_class": None,
        "location": None,
    }

    for i in range(n):
        is_buggy = (i % 2 == 0)
        tmpl = buggy_templates[i % len(buggy_templates)] if is_buggy else clean_template
        records.append(
            {
                "id": f"synthetic_{i:04d}",
                "source_code": tmpl["source_code"],
                "has_bug": is_buggy,
                "bug_class": tmpl["bug_class"] if is_buggy else None,
                "location": tmpl["location"] if is_buggy else None,
                "description": "Synthetic record generated by prepare_bugs4q.py",
            }
        )

    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / "bugs4q.json"
    with out_file.open("w") as fh:
        json.dump(records, fh, indent=2)
    logger.info("Wrote %d records to %s", len(records), out_file)


def _convert_local(source: Path, out_dir: Path) -> None:
    """
    I convert an existing local Bugs4Q directory or JSON file into the
    expected format.
    """
    logger.info("Converting local source %s → %s", source, out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    if source.is_file() and source.suffix == ".json":
        shutil.copy(source, out_dir / "bugs4q.json")
        logger.info("Copied %s → %s/bugs4q.json", source, out_dir)
    elif source.is_dir():
        for json_file in source.glob("*.json"):
            shutil.copy(json_file, out_dir / json_file.name)
        logger.info("Copied JSON files from %s → %s", source, out_dir)
    else:
        logger.warning("Unsupported source format: %s", source)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--source",
        type=str,
        default=None,
        help=(
            "Path to a local Bugs4Q JSON file or directory. "
            "If omitted, I generate a small synthetic dataset."
        ),
    )
    parser.add_argument(
        "--out",
        type=str,
        default=str(DEFAULT_OUT),
        help=f"Output directory for prepared data (default: {DEFAULT_OUT})",
    )
    parser.add_argument(
        "--synthetic-n",
        type=int,
        default=20,
        help="Number of synthetic records to generate when no --source is given (default: 20)",
    )
    parser.add_argument("--log-level", default="INFO")
    args = parser.parse_args()

    setup_logging(args.log_level)
    out_dir = Path(args.out)

    if args.source:
        source = Path(args.source)
        if not source.exists():
            logger.error("Source path does not exist: %s", source)
            sys.exit(1)
        _convert_local(source, out_dir)
    else:
        logger.info(
            "No --source provided.  Generating %d synthetic records.\n"
            "For the real dataset see: %s",
            args.synthetic_n,
            BUGS4Q_REPO,
        )
        _make_synthetic_dataset(out_dir, n=args.synthetic_n)

    logger.info("Dataset preparation complete.  Data is in: %s", out_dir)


if __name__ == "__main__":
    main()
